declare type LangJsonData = Record<Exclude<SupportedLanguage, 'lemon'>, LanguageData>;
declare let LANGJSON: LangJsonData;
declare let allLangJsons: LanguageData[];
declare function fillLanguageIdentifiers(identifier: string): void;
declare function applyEnglishKey(identifier: string, value: string): void;
declare function setupLangJSON(download?: boolean): Promise<void>;
declare function langCreateCSV(): Promise<void>;
declare function formatStringForCSV(text: string): string;
declare function buildCSVFile(headers: string[], rows: string[][]): string;
declare function convertJSONtoCSV(): Promise<string>;
declare function langGenerateErrorText(): void;
declare function langGeneratePushNotifications(): void;
declare function langGenerateToasts(): void;
declare function langGenerateMilestoneStrings(): void;
declare function langGenerateGolbinRaidStrings(): void;
declare function langGenerateGameGuideStrings(): void;
declare function langGenerateSettingsStrings(): void;
declare function langGenerateAstrologyStrings(): void;
declare function langGeneratePageNameMisc(): void;
declare function langGenerateTutorialText(): void;
declare function langGenerateIAPStrings(): void;
declare function langGenerateCompletionText(): void;
declare function langGenerateStatisticsText(): void;
declare function langGenerateMenuText(): void;
declare function langGenerateMagicText(): void;
declare function langGenerateBankText(): void;
declare function langGenerateEquipSlotNameText(): void;
declare function langGenerateMiscCombatText(): void;
declare function langGenerateMiscShopText(): void;
declare function langGenerateFarmingMiscText(): void;
declare function langGenerateCharacterSelectText(): void;
declare function langGenerateMiscText(): void;
declare function langGenerateGamemodeText(): void;
declare function langGenerateThievingText(): void;
declare function langGenerateEndgameText(): void;
declare function langGeneratePrayer(): void;
declare function langGenerateSpecialAttackDescriptions(): void;
declare function langGenerateSkillNames(): void;
declare function langGeneratePetText(): void;
declare function langGenerateLore(): void;
declare function langGeneratePrivacyPolicy(): void;
declare function langGenerateShopText(): void;
declare function langGenerateModifierData(): void;
declare function langGenerateNumberShorthand(): void;
declare function langGenerateEquipStatText(): void;
declare function langGenerateTimeUnits(): void;
declare function langGenerateEventStrings(): void;
declare function langGenerateTownship(): void;
declare function langGenerateTownshipMenu(): void;
declare function langGenerateFromDataPackage(dataPackage: GameDataPackage): void;
